### PR TITLE
make: code refactoring

### PR DESCRIPTION
**Pull request by gapry**
The following list is the summary of PR

* define a control flow to determine the proper compiler prefix
* define the LIBS flags
* extend the CFLAGS
* modify the check target rule
* modify the amacc target rule
* define the src and apply it

### CODE REVIEW

**Comment by gapry** [comment]
@jserv the conflict is solved

**Comment by jserv** [comment]
Please perform `git rebase origin/master`.

**Comment by gapry** [comment]
I have done.  Doesn't work !?

**Comment by jserv** [comment]
@gapry : If you did perform `git rebase` properly, there is no commit "Merge remote-tracking branch 'upstream/master' ...".

**Pull request merged**
