### PR TITLE
make: prevent the case of recipe for target failed

### PR DESCRIPTION
**Pull request by gapry**
let it can execute tests/hello.c

### CODE REVIEW

**Comment by jserv** [comment]
What kind of problem do you exactly wish to resolve? I would expect the improvements over existing test suite.

**Comment by gapry** [comment]
Without the patch, you will see the following error messages

```
could not open(elf/amacc)
Makefile:29: recipe for target 'elf/amacc' failed
make: *** [elf/amacc] Error 255
```

it can not execute test-suite.

Is the problem  no meanless as I solve the ELF loader ?

**Comment by gapry** [comment]
Is the problem no meanless as I solve the ELF loader ? That means, do you prefer I solve the ELF32 Loader directly?

**Comment by gapry** [comment]
I have update the context of PR 
commit: https://github.com/jserv/amacc/pull/15/commits/6ec472ddf948103f46599edf6c6e0c546839c4df

the commit make sure the elf directory is created or is deleted

**Comment by gapry** [comment]
it duplicates PR #17

**Pull request closed without merging**
